### ISSUE TITLE
CelSpecParser.js:4 Uncaught ReferenceError: Myna is not defined

### ISSUE THREAD

**Issue by dwilt** [Fleker/cel-js#2]
@Fleker Thanks so much for building this project! We're looking at using it for one of our products (will keep you posted on that). Trying to get a sandbox of this off the ground to see how it works. Take a look here: https://codesandbox.io/p/devbox/2kqz35?file=%2Fsrc%2Findex.ts. This sandbox is public so feel free to update it however you see fit. Please just let me know what changes you make so I understand what you changed.

I added `myna-parser` as a dependency (btw, your install instructions should probably include that as this will most likely confuse others) so the library is there. 

In GH, I see [that `CelSpecParser.ts`](https://github.com/Fleker/cel-js/blob/master/src/CelSpecParser.ts#L1) has the `import` from `myna-parser` at the top but [what you currently have published to NPM](https://www.npmjs.com/package/@fleker/cel-js?activeTab=code) does not:

![image](https://github.com/Fleker/cel-js/assets/1065539/0dc72113-3956-44f5-b842-a34d07e6e6ea)

Please let me know if I'm missing something.

Having a public sandbox with a working demo of your library here would be super helpful for others most likely too!

**Comment by Fleker** [comment]
Hey thanks for taking a look through the code. The primary use of the project has been as an advanced search capability for [a Pokemon web game](https://github.com/Fleker/pokemon-as-a-service). In particular, I do have to [modify index.html](https://github.com/Fleker/pokemon-as-a-service/blob/main/client/src/index.html)  to do a working import:

```
  <script>
    // https://github.com/cdiggins/myna-parser/issues/15
  var exports = {}
  </script>
  <script src="https://unpkg.com/myna-parser@2.5.1/myna.js">
```

I'll take an action item to put together a public sandbox since that should help with future development.

**Comment by Fleker** [comment]
Good evening @dwilt I've put together a hosted implementation of this library for demoing

https://felker.dev/cel-js/

This demo shows how things go together and how to handle a few different types of data. I hope this gives you some guidance.
